import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Quicksand } from "next/font/google";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <main className="bg-[#FC6865] flex h-[800px] w-full items-start justify-center text-white px-4">
          <div className="max-w-screen-lg mx-auto max-h-[480px] flex-1">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
